import type { NextPage } from "next";
import Head from "next/head";
import ArtBlock from "../components/ArtBlock/ArtBlock";
import Info from "../components/Info/Info";
import Main from "../components/Main/Main";
import styles from "../styles/Home.module.css";

let buttonClick = (): void => {
  console.log("test");
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
        LeftSection={
          <Info
            hasButton={true}
            buttonText="See my Work"
            textInfo={[
              { class: "title", text: "test fear test bear" },
              { class: "subTitle", text: "test test" },
              { class: "paragraph", text: "testtttttttttttttt" },
            ]}
            hasImage={false}
          />
        }
        RightSection={<ArtBlock />}
      />
    </div>
  );
};

export default Home;
