import type { NextPage } from "next";
import Head from "next/head";
import AboutCard from "../components/AboutCard/AboutCard";
import ArtBlock from "../components/ArtBlock/ArtBlock";
import Grid from "../components/Grid/Grid";
import Info from "../components/Info/Info";
import Main from "../components/Main/Main";
import styles from "../styles/Home.module.css";

let buttonClick = (): void => {
  console.log("test");
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
        LeftSection={
          <Info
            index={0}
            hasButton={true}
            buttonText="See my Work"
            textInfo={[
              {
                class: "paragraph gray",
                text: "web developer /ui-ux designer",
              },
              {
                class: "subTitle",
                text: "I translate your requirements into powerfull , beautifull and responsive websites",
              },
            ]}
            hasImage={false}
          />
        }
        RightSection={<ArtBlock />}
      />

      <Main
        LeftSection={
          <Info
            index={1}
            hasButton={false}
            textInfo={[
              {
                class: "subTitle",
                text: "Are you still wasting time finding good web developers!",
              },
              {
                class: "paragraph",
                text: "A good web developer is someone who is thirsty for new knowladge,seeker for improvments and has willingness to fix errors whethers with team or by himself",
              },
              { class: "subTitle", text: "if yes .. Here comes my turn." },
              {
                class: "paragraph",
                text: "With more than 2 years of expreince in web development,Passionate about making websites ,Interacting with it and decover new web hacks ",
              },
            ]}
            hasImage={false}
          />
        }
        RightSection={
          <Grid
            direction="column-reverse"
            quadContainer
            Child={<AboutCard />}
          />
        }
      />
    </div>
  );
};

export default Home;
