import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Info from "../components/utils/Info";
import Main from "../components/layout/Main";
import childrenHelper from "../helpers/mainChildrensHelper";
import infos from "../infos/homeComponentsInfos";
import { mainInfos } from "../types/info";

interface PageProps {
  pageInfo: mainInfos;
}
const Home: NextPage<PageProps> = ({ pageInfo }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {pageInfo.map((info, index) => {
        return (
          <Main
            key={index}
            LeftSection={
              <Info
                hasButton={info.info.hasButton}
                buttonText={info.info.buttonText}
                textInfo={info.info.textInfo}
                hasImage={info.info.hasImage}
              />
            }
            RightSection={childrenHelper(
              info.right.name,
              info.right.properties,
              info.right.childName
            )}
          />
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => ({
  props: { pageInfo: infos },
});
export default Home;
