import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ArtBlock from "../components/ArtBlock/ArtBlock";
import Header from "../components/Header/Header";
import Layout from "../components/layout/Layout";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Link href="/">
        <a style={{ fontSize: 100, zIndex: 100, background: "red" }}>
          return to home
        </a>
      </Link>
    </div>
  );
};

export default Test;
