import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Info from "../components/utils/Info";
import Main from "../components/layout/Main";
import childrenHelper from "../helpers/mainChildrensHelper";
import infos from "../infos/workComponentsInfos";
import { PageProps } from "../types/pages";

const Work: NextPage<PageProps> = ({ pageInfo }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {pageInfo.map((info, index) => {
        return (
          <Main
            key={index}
            reverseLayout={info.reverseLayout}
            LeftSection={
              <Info
                background={info.info.background}
                isContact={info.info.isContact}
                hasButton={info.info.hasButton}
                buttonText={info.info.buttonText}
                textInfo={info.info.textInfo}
                hasImage={info.info.hasImage}
              />
            }
            RightSection={childrenHelper(
              info.right.name,
              info.right.properties,
              info.right.childName,
              info.right.childProps
            )}
          />
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = (context) => {
  return {
    props: { pageInfo: infos },
  };
};
export default Work;
